use_frameworks!

platform :ios, '12.0'

target 'SHLocalized_Example' do
  pod 'SHLocalized', :path => '../'

  target 'SHLocalized_Tests' do
    inherit! :search_paths
    pod 'SHLocalized', :path => '../'
    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      
    end
  end
  
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['CODE_SIGN_IDENTITY'] = ''
  end
end
